services:
  profile-db:
    image: postgres:latest
    container_name: profile-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: profile_db
    ports:
      - "5434:5432"
    volumes:
      - profile_data:/var/lib/postgresql
    restart: always

  identity-db:
    image: postgres:latest
    container_name: identity-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"
    volumes:
      - identity_data:/var/lib/postgresql
    restart: always

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  profile_data:
  identity_data: